"""Jupyter Notebook에서 Streamlit을 사용하는 예시입니다."""

# AUTOGENERATED! DO NOT EDIT! File to edit: streamlit-jupyter_example.ipynb.

# %% auto 0
__all__ = []

# %% streamlit-jupyter_example.ipynb 2
from datetime import datetime

import streamlit as st

from streamlit_jupyter import StreamlitPatcher, tqdm

# %% streamlit-jupyter_example.ipynb 4
st.title("Example")

# %% streamlit-jupyter_example.ipynb 5
st.markdown(
    """

streamlit_jupyter의 사용 예를 보여주는 테스트 페이지입니다.

Jupyter에서 해당 메시지를 보신다면, 잘 작동하고 있습니다!

"""
)

# %% streamlit-jupyter_example.ipynb 7
name = st.text_input("이름을 입력하세요", "라이캣")

# %% streamlit-jupyter_example.ipynb 8
date = st.date_input("날짜를 선택하세요.", datetime.now().date())

# %% streamlit-jupyter_example.ipynb 9
st.markdown(f"## Hello {name}!\n## 오늘 날짜는 {date.strftime('%Y-%m-%d')}")

# %% streamlit-jupyter_example.ipynb 10
import time

import pandas as pd

st.subheader("Cached 데이터프레임")

@st.cache_data()
def get_data(date):
    for i in tqdm(range(10)):
        time.sleep(0.1)
    return pd.DataFrame(
        {"date": pd.date_range(date, periods=3), "c": [7, 8, 5], "d": [10, 11, 7]}
    ).set_index("date")


df_date = get_data(date)
st.write(df_date)

# %% streamlit-jupyter_example.ipynb 11
st.subheader("Data Editor")
df = pd.DataFrame(
    [
       {"command": "st.selectbox", "rating": 4, "is_widget": True, },
       {"command": "st.balloons", "rating": 5, "is_widget": False, },
       {"command": "st.time_input", "rating": 3, "is_widget": True,},
   ]
)
edited_df = st.data_editor(df)

# %% streamlit-jupyter_example.ipynb 12
st.subheader("Cache 예시")
@st.cache_resource(ttl=3600)
def get_resource():
    st.write("Getting resource...")
    for i in tqdm(range(5)):
        time.sleep(0.1)
    return {
        "foo": "bar",
        "baz": [1, 2, 3],
        "qux": {"a": 1, "b": 2, "c": 3},
    }


records = get_resource()
st.json(records)

# %% streamlit-jupyter_example.ipynb 14
st.subheader("Ploting")

import plotly.express as px

df_daily = df_date.mean(axis=1).rename("daily_average")
fig = px.line(df_daily, title="Daily mean", width=600)
st.write(fig)

# %% streamlit-jupyter_example.ipynb 15
st.metric("Speed", 300, 210)

# %% streamlit-jupyter_example.ipynb 16
st.code("print(1+1)", language="python")

# %% streamlit-jupyter_example.ipynb 17
show_code = st.checkbox("Show code", value=True)

# %% streamlit-jupyter_example.ipynb 18
if show_code:
    st.code("[i**2 for i in range(100)]")

# %% streamlit-jupyter_example.ipynb 19
option = st.radio("Choose one option", options=["foo", "bar"], index=1)

# %% streamlit-jupyter_example.ipynb 20
option = st.selectbox("Selectbox: ", options=["LiCat", "Garry", "SoulGom"], index=0)

# %% streamlit-jupyter_example.ipynb 21
options = st.multiselect("Multiselect: ", options=["Python", "Golang", "Julia", "Rust"])

# %% streamlit-jupyter_example.ipynb 22
options = st.multiselect(
    "Multiselect with defaults: ",
    options=["nbdev", "streamlit", "jupyter", "fastcore"],
    default=["jupyter", "streamlit"],
)

# %% streamlit-jupyter_example.ipynb 23
st.subheader("st.text:")
st.text("텍스트 문구입니다.")
st.text("이것은 \n 여러 줄의 텍스트입니다.")
st.code("이것은 여러 줄의 \n 코드입니다", language=None)
